/// <reference types="node" />
import { resolve } from 'path';
import { defineConfig } from 'vite';
import type { FetchLike } from 'xiv-api-provider/datamine';
import { dataminePolyfill } from 'xiv-datamine-polyfill/plugin';

/**
 * A consumer's own vite config: this project's `src/index.ts` imports two `xiv-datamine-polyfill/<Sheet>.csv`
 * modules, so the plugin runs inside a real build of real target code rather than inside a test that calls a
 * bundler. The build output is `dist/index.js`, and `rushx test` runs it — the generated module resolving,
 * surviving bundling and holding the trimmed data is what "the run is normal" means here.
 *
 * Offline by default: the sheets are served by a stub fetch below, so CI's `rush build` needs no network and
 * the generated bytes are reproducible. `XIV_LIVE=1` drops the stub and sets `maxAge: 0`, which forces one
 * genuine round trip through `raw.githubusercontent.com`, the parser and the cache.
 */
const live = process.env.XIV_LIVE === '1';

const ITEM_UI = ['key,0,1', '#,Name,Icon', 'int32,str,Image', '0,"",0', '1,"格斗武器",60101', '2,"单手剑",60102'].join('\n');
const ADDON = ['key,0,1', '#,Text,Name', 'int32,str,str', '699,"即时",Common', '700,"> ",Common', '999,"<Switch(1,2,3,4)>",Generic'].join('\n');

/** Answer by the sheet name in the requested path; anything else is a 404, which is a real answer about data. */
const stubFetch = (async (input: string | URL | Request) => {
  const url = new URL(String(input));
  console.log(`[e2e] sheet request: ${url.pathname}`);
  const sheet = decodeURIComponent((url.pathname.split('/').pop() ?? '').replace(/\.csv$/, ''));
  const body = sheet === 'ItemUICategory' ? ITEM_UI : sheet === 'Addon' ? ADDON : undefined;
  return new Response(body ?? '', { status: body === undefined ? 404 : 200 });
}) as FetchLike;

export default defineConfig({
  plugins: [
    dataminePolyfill({
      sheets: {
        ItemUICategory: { columns: ['#', 'Name'], dropEmptyIn: 'Name' },
        Addon: { columns: ['#', 'Text'], onlyRowKeys: ['699', '700'] },
      },
      // A separate cache per mode: otherwise one live run leaves the real sheets in the folder the offline
      // build reads from, and `rushx test` stops being the deterministic stub run it claims to be.
      cacheDir: resolve(import.meta.dirname, 'node_modules', '.cache', live ? 'xiv-datamine-polyfill-e2e-test-live' : 'xiv-datamine-polyfill-e2e-test'),
      fetch: live ? undefined : stubFetch,
      maxAge: live ? 0 : undefined,
    }),
  ],
  build: {
    target: 'esnext',
    lib: { entry: resolve(import.meta.dirname, 'src/index.ts'), formats: ['es'], fileName: () => 'index.js' },
  },
});
