/// <reference types="node" />
import { builtinModules } from 'node:module';
import { resolve } from 'path';
import dts from 'unplugin-dts/vite';
import { defineConfig } from 'vite';

// A Node-side package: `load.ts` and `cache.ts` reach for `node:fs`, `node:path` and `node:crypto`, and
// without the builtins listed here vite treats those as something a browser would need a shim for.
const nodeBuiltins = new Set([...builtinModules, ...builtinModules.map((name) => `node:${name}`)]);

/**
 * One entry, one file: `src/index.ts` holds both things a caller does with a sheet — install the plugin in a
 * build, or take a table outside one.
 *
 * Every import inside `src/` is relative, which is what keeps the generated declarations free of a specifier
 * only this package understands; `@/` is reserved for `test/`. That predates the bundling and survives it:
 * the declarations are now generated in the same pass as the JavaScript, by the same resolver, so a specifier
 * a consumer cannot read has no way to survive into `dist/`.
 */
export default defineConfig({
  plugins: [
    dts({
      // Only `src/` is public surface. `tsconfig.app.json` names it alongside the hand-written
      // `client.d.ts` this package ships as `./client`.
      tsconfigPath: 'tsconfig.app.json',
      bundleTypes: true,
      // `exports` is hand-maintained, including `./client`, whose declaration is authored by hand at the
      // package root and is not generated by anything here.
      insertTypesEntry: false,
    }),
  ],
  build: {
    outDir: resolve(import.meta.dirname, 'dist'),
    emptyOutDir: true,
    target: 'node24',
    minify: false,
    sourcemap: true,
    lib: {
      entry: { index: resolve(import.meta.dirname, 'src/index.ts') },
      formats: ['es'],
    },
    rolldownOptions: {
      // The providers are real dependencies that a build resolves for itself — inlining them would put a second
      // copy of the fetch and parse code inside the plugin, and the cache is the datamine provider's to own.
      // `api-sdk-framework` is external for the same reason `ApiError` is the failure type a caller branches on:
      // a second copy inside this bundle would break `instanceof` against the caller's own import. `vite` is the
      // peer this plugin plugs into.
      external: (id) => nodeBuiltins.has(id) || /^xiv-datamine-provider(\/|$)/.test(id) || /^api-sdk-framework(\/|$)/.test(id) || /^vite(\/|$)/.test(id),
      output: { entryFileNames: '[name].js' },
    },
  },
  resolve: {
    alias: {
      '@': resolve(import.meta.dirname, 'src'),
    },
  },
});
